apiVersion: v1
kind: Pod
metadata:
  name: ceph-connector
spec:
  containers:
  - name: ceph-app
    image: python:3.9
    command: ["python", "-c", "import os; print(f'Access Key: {os.environ[\"S3_ACCESS_KEY\"]}')"]
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
    env:
    - name: S3_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: ceph-s3-credentials
          key: access-key
    - name: S3_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: ceph-s3-credentials
          key: secret-key
    - name: S3_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: ceph-s3-credentials
          key: endpoint
    envFrom:
    - secretRef:
        name: ceph-s3-credentials
