apiVersion: v1
kind: Pod
metadata:
  name: ceph-connector-secure
spec:
  containers:
  - name: ceph-app
    image: python:3.9
    command: ["sh", "-c", "cat /etc/ceph-credentials/s3-credentials.txt && sleep 1000"]
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
    volumeMounts:
    - name: ceph-creds
      mountPath: /etc/ceph-credentials
      readOnly: true
  volumes:
  - name: ceph-creds
    secret:
      secretName: s3-credentials
      defaultMode: 0600
